# Generated by Django 3.2.8 on 2022-12-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_film', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('namaFilm', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tanggal', models.DateField()),
                ('durasi', models.TimeField()),
                ('genre', models.TextField()),
                ('batasanUmur', models.CharField(max_length=3)),
                ('cast', models.TextField()),
            ],
        ),
    ]
