# Generated by Django 4.1 on 2022-12-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="fullName", new_name="full_name",
        ),
    ]
